# Generated by Django 3.1.1 on 2020-10-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.BigIntegerField(default='0', unique=True),
        ),
    ]
