# Generated by Django 3.1.1 on 2020-10-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userabstract',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
