# Generated by Django 3.1.1 on 2020-10-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20201005_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
