# Generated by Django 3.1.1 on 2020-10-07 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201001_1517'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0005_remove_teacher_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='abc', max_length=30)),
                ('last_name', models.CharField(default='xyz', max_length=30)),
                ('email', models.EmailField(default='abc@gmail.com', max_length=254, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('registered', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
