# Generated by Django 3.1.1 on 2020-10-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20201007_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregister',
            name='active',
        ),
        migrations.RemoveField(
            model_name='preregister',
            name='course',
        ),
    ]
