# Generated by Django 3.1.1 on 2020-10-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201001_1517'),
        ('teacher', '0007_auto_20201007_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregister',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preregister',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
    ]
