# Generated by Django 3.1.1 on 2020-10-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20201007_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userabstract',
            name='semester',
        ),
    ]
