# Generated by Django 3.1.1 on 2020-10-10 07:29

from django.db import migrations, models
import django.db.models.deletion
import register_book.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('subject', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('total_classes', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('open', models.BooleanField(default=False)),
                ('semester', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=register_book.models.current_year)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.userabstract')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
