# Generated by Django 3.1.1 on 2020-10-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_book', '0002_auto_20201010_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbook',
            name='professor',
        ),
    ]
