# Generated by Django 3.1.1 on 2020-10-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_book', '0003_remove_registerbook_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbook',
            name='description',
        ),
    ]
