# Generated by Django 3.1.1 on 2020-10-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'course', 'name')},
        ),
    ]
