# Generated by Django 3.1.1 on 2020-10-08 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_userabstract_semester'),
        ('courses', '0004_auto_20201001_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.userabstract'),
        ),
    ]
