# Generated by Django 3.1.1 on 2020-10-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_userabstract_semester'),
        ('courses', '0006_auto_20201008_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.userabstract'),
        ),
    ]
