# Generated by Django 3.1.1 on 2020-10-08 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_subject_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
