# Generated by Django 3.1.1 on 2020-10-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=2020),
        ),
    ]
