# Generated by Django 3.1.1 on 2020-10-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'name')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
