# Generated by Django 3.1.1 on 2020-10-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_subject'),
        ('subject', '0002_auto_20201008_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('semester', 'course', 'name')},
        ),
    ]
