# Generated by Django 3.1.1 on 2020-10-08 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0004_auto_20201008_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
