# Generated by Django 3.1.1 on 2020-10-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_remove_userabstract_semester'),
        ('subject', '0005_remove_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.userabstract'),
        ),
    ]
