# Generated by Django 3.1.1 on 2020-10-15 06:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('register_book', '0005_auto_20201014_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('half', models.IntegerField(default=1)),
                ('date_attendance', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('register_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_book.registerbook')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.userabstract')),
            ],
            options={
                'unique_together': {('register_book', 'student', 'date_attendance', 'half')},
            },
        ),
    ]
